#!/bin/sh
# set -eu

echo "[auditron] Auditron starting at $(date -Is)" > /dev/kmsg 2>/dev/null || true
echo "[auditron] mounting /proc /sys /dev"
mount -t proc proc /proc 2>/dev/null || true
mount -t sysfs sys /sys 2>/dev/null || true
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true

REPORT_DIR="/run/auditron"
BOOTHASH="/var/lib/auditron/boothash"
REPORT_JSON="${REPORT_DIR}/report.json"
DEFS="/usr/local/lib/auditron/definitions.json"

mkdir -p "$REPORT_DIR"

echo "{\"started\":\"$(date -Is)\",\"checks\":[]}" > "$REPORT_JSON"


[ -f "$BOOTHASH" ] && mv "$BOOTHASH" "$BOOTHASH".prev
find /boot -type f -exec sha256sum {} + | sort | sha512sum > "$BOOTHASH"
sleep 2


if [ -f "$DEFS" ]; then
  echo "[auditron] definitions found; auditing the system..."
  rulecount=$(jq '.rules | length' "$DEFS")
  i=0
  while [ "$i" -lt "$rulecount" ]; do
    id=$(jq -r ".rules[$i].id" "$DEFS")
    desc=$(jq -r ".rules[$i].description" "$DEFS")
    type=$(jq -r ".rules[$i].type" "$DEFS")
    path=$(jq -r ".rules[$i].path" "$DEFS")
    pattern=$(jq -r ".rules[$i].pattern" "$DEFS")
    action=$(jq -r ".rules[$i].action" "$DEFS")
    eval "expanded_path=\"$path\""
    if [[ "$pattern" == /* ]]; then
	  clean_pattern="${pattern#/}"
	  matches=$(find "$expanded_path" -maxdepth 1 -type f -name "$clean_pattern" 2>/dev/null || true)
	else
	  matches=$(find "$expanded_path" -type f -name "$pattern" 2>/dev/null || true)
	fi
	if [ -n "$matches" ]; then
	  tmpf="$(mktemp)"
	  case "$type" in
		file)
	        for f in $matches; do
	          # jq --arg id "$id" --arg desc "$desc" --arg path "$f" \
	          	  # '.checks += [{"id":$id,"description":$desc,"status":"FOUND","path":$path,"action":$ARGS.named.action}]' --arg action "$action" "$REPORT_JSON" > "$tmpf" && mv "$tmpf" "$REPORT_JSON" || true
	          jq --arg id "$id" --arg desc "$desc" --arg path "$f" --arg action "$action" \
	          	  '.checks += [{"id":$id,"description":$desc,"status":"FOUND","path":$path,"action":$action}]' "$REPORT_JSON" > "$tmpf" && mv "$tmpf" "$REPORT_JSON" || true
			  if [ "$action" = "quarantine" ]; then
				  chown -R auditron:users "$f"
	        	  chmod -R 600 "$f"
	          fi
	        done
		    ;;
		permission)
			perm=$(jq -r ".rules[$i].perm" "$DEFS")
			for f in $matches; do
				info=$(stat -c "%u:%g:%a" "$f")
				[[ "$info" != "$perm" ]] && jq --arg id "$id" --arg desc "$desc" --arg path "$f" '.checks += [{"id":$id,"description":$desc,"status":"FOUND","path":$path,"action":$ARGS.named.action}]' --arg action "$action" "$REPORT_JSON" > "$tmpf" && mv "$tmpf" "$REPORT_JSON" || true
				IFS=":" read -r uid gid p <<< "$perm"
				chown "$uid:$gid" "$f"
				chmod "$p" "$f"
			done
			;;
		suid)
			for f in $matches; do
				[ -u "$f" ] && jq --arg id "$id" --arg desc "$desc" --arg path "$f" '.checks += [{"id":$id,"description":$desc,"status":"FOUND","path":$path,"action":$ARGS.named.action}]' --arg action "$action" "$REPORT_JSON" > "$tmpf" && mv "$tmpf" "$REPORT_JSON" || true
				chmod u-s "$f"
			done
			;;
		sgid)
			for f in $matches; do
				[ -g "$f" ] && jq --arg id "$id" --arg desc "$desc" --arg path "$f" '.checks += [{"id":$id,"description":$desc,"status":"FOUND","path":$path,"action":$ARGS.named.action}]' --arg action "$action" "$REPORT_JSON" > "$tmpf" && mv "$tmpf" "$REPORT_JSON" || true
				chmod g-s "$f"
			done
			;;
	  esac
	fi
    i=$((i+1))
  done
else
  echo "[auditron] no definitions found"
fi
echo "[auditron] report written to $REPORT_JSON"

read

exec /sbin/init "$@"
